name: Nerdgirlmax
favicon: null
layout_spectrum: 0.015040797181427479
typography_spectrum: 0.12106949067674577
title: 'A galaxy of nerdom, geekity, and the interests in between.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7742295057978481
  lightness: 0.14233676926232874
  saturation: 0.4947469565086067
  rhythmicContrast: 0.12415031180717051
purpose: []
